language: node_js     
node_js:
- stable
branches:
  only:
  - master
before_script:
- npm install -g bower
- npm install gulp
- bower install
script: 
- git config user.email "travis@mutualab.org";git config user.name "Travis deployment"
- git remote set-url origin https://${GH_TOKEN}@${GH_REF} > /dev/null 2>&1
- git remote set-branches --add origin gh-pages
- git fetch --all > /dev/null 2>&1
- gulp build:ftp
cache:
  directories:
  - node_modules
  - bower_components

notifications:
  email: false
  slack: mutualab:5SoNAVBR0TKFLgjhsiFetwER